# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(710, 480, 261, 41))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(710, 10, 261, 461))
        self.listWidget.setObjectName("listWidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 691, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(980, 120, 161, 261))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPasteGame = QtWidgets.QAction(MainWindow)
        self.actionPasteGame.setObjectName("actionPasteGame")
        self.actionConnectEngine = QtWidgets.QAction(MainWindow)
        self.actionConnectEngine.setObjectName("actionConnectEngine")
        self.actionConnectDB = QtWidgets.QAction(MainWindow)
        self.actionConnectDB.setObjectName("actionConnectDB")
        self.actionAboutProgram = QtWidgets.QAction(MainWindow)
        self.actionAboutProgram.setObjectName("actionAboutProgram")
        self.menu.addAction(self.actionConnectEngine)
        self.menu_2.addAction(self.actionConnectDB)
        self.menu_4.addAction(self.actionPasteGame)
        self.menu_5.addAction(self.actionAboutProgram)
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wakaranai"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить запись игры в БД"))
        self.menu.setTitle(_translate("MainWindow", "Движок"))
        self.menu_2.setTitle(_translate("MainWindow", "БД"))
        self.menu_3.setTitle(_translate("MainWindow", "Файл"))
        self.menu_4.setTitle(_translate("MainWindow", "Правка"))
        self.menu_5.setTitle(_translate("MainWindow", "Помощь"))
        self.actionPasteGame.setText(_translate("MainWindow", "Вставить игру"))
        self.actionConnectEngine.setText(_translate("MainWindow", "Подключение"))
        self.actionConnectDB.setText(_translate("MainWindow", "Подключение"))
        self.actionAboutProgram.setText(_translate("MainWindow", "О программе"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
